apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
     path: /mnt/pv-data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default

